"""add bank connections

Revision ID: d705322cd5f4
Revises: d779bfd363c6
Create Date: 2026-09-02 02:41:23.524132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd705322cd5f4'
down_revision: Union[str, Sequence[str], None] = 'd779bfd363c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'connections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'user_id')
    # ### end Alembic commands ###
